version: "3.9"

services:
  go_db:
    container_name: go_db
    image: postgres:12
    enviroment:
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: postgres
      POSTGRES_DB: gocrud
    ports:
      - "5432:4444"
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata: {}
